using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using FieldApp.Application.Items;

namespace FieldApp.Infrastructure.Storage;

/// <summary>
/// Photos in a private Azure Blob Storage container (Azurite locally). Blob keys are generated by the server; the
/// browser never receives account keys, SAS tokens or blob URLs.
/// </summary>
internal sealed class AzureBlobPhotoStorage(PhotoContainerProvider containers) : IPhotoStorage
{
    public async Task UploadAsync(string key, Stream content, string contentType, CancellationToken cancellationToken)
    {
        try
        {
            await containers.Container.GetBlobClient(key).UploadAsync(
                content,
                new BlobUploadOptions { HttpHeaders = new BlobHttpHeaders { ContentType = contentType } },
                cancellationToken);
        }
        catch (RequestFailedException ex)
        {
            throw new PhotoStorageException("Photo storage rejected the upload.", ex);
        }
    }

    public async Task<StoredObject?> GetPropertiesAsync(string key, CancellationToken cancellationToken)
    {
        try
        {
            var properties = await containers.Container.GetBlobClient(key).GetPropertiesAsync(cancellationToken: cancellationToken);
            return new StoredObject(properties.Value.ContentLength, properties.Value.ContentType);
        }
        catch (RequestFailedException ex) when (ex.Status == 404)
        {
            return null;
        }
        catch (RequestFailedException ex)
        {
            throw new PhotoStorageException("Photo storage is unavailable.", ex);
        }
    }

    public async Task<Stream> OpenReadAsync(string key, CancellationToken cancellationToken)
    {
        try
        {
            return await containers.Container.GetBlobClient(key).OpenReadAsync(cancellationToken: cancellationToken);
        }
        catch (RequestFailedException ex)
        {
            throw new PhotoStorageException("Photo storage is unavailable.", ex);
        }
    }
}
